### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: No match found

### ISSUE THREAD

**Issue by Daniel-Ze** [steuernb/NLR-Parser#3]
Hi,
I wanted to try the program NLR-parser however I get an error when I try running it:

Exception in thread "main" java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:645)
	at coreClasses.MastEntry.<init>(MastEntry.java:27)
	at coreClasses.MastXMLReader.readEntry(MastXMLReader.java:95)
	at coreClasses.MastFile.readEntries(MastFile.java:70)
	at coreClasses.MastFile.<init>(MastFile.java:65)
	at coreClasses.NLRParser.main(NLRParser.java:106)

JRE version:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

Meme-suite version:
meme                      5.0.2           py36pl526h96dd833_5    bioconda

NLR-parser version:
latest release 1.0

I ran mast with the meme.xml from your GitHub page:
mast -o /path/to/my/output meme.xml /path/to/my/fasta/fasta.fa

Results are present and mast.html can be viewed.

I ran NLR-parser with the mast.xml output from mast:
java -jar /path/to/NLR-parser.jar -i /path/to/mast_out/mast.xml -o /path/to/output/out.nlrparser.txt -a /path/to/my/fasta/fasta.fa

This throws the error from above.
What do I need to change to get the program running?

Cheers,
Daniel

**Comment by steuernb** [comment]
Hi Daniel,
It is most likely the meme version. They changed the output format of mast with 5.0. Any version newer than 4.9 will not work with NLR-Parser.
Could you try this and we see from there?
All the best
Burkhard

**Comment by Daniel-Ze** [comment]
Hi Burkhard,
while running the make command for meme-suite 4.9.1 I get an error (also with other versions).
Is there any special requirements for make? I'm on a MacBook Pro with Mojave installed.
Cheers,
Daniel

**Comment by Daniel-Ze** [comment]
ld: 42 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [ama] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

That's the error.

**Comment by steuernb** [comment]
Hi Daniel,
Sorry, I am no expert for the meme suite, or installing software on macs. I have once tried to install it on a mac (other version though) and the overall process failed. However, mast was working to the extent that it created the correct xml output. That would be enough for NLR-Parser. If that does not work you can try to install it in a VM. Download Virtual Box, install Linux and meme in there. Last option, if it is a one-off thing, I can run your data for you.
All the best
Burkhard

**Comment by Daniel-Ze** [comment]
Hi Burkhard,
I got the right version of meme-suite running and as far as I can tell NLR-parser is doing its job.
It was some compiler problems combined with missing PATH links... 
Thanks for the offer of running it for me though. Appreciate it!
Cheers,
Daniel
