### ISSUE TITLE
Question about differences between passing anotated amino acid sequences and nucleotide sequences to NLR-parser

### ISSUE THREAD

**Issue by b524198065** [steuernb/NLR-Parser#4]
Dear developers:

Since NLR-parser is capable to translate DNA sequcnes to amino acid sequnces in a 6-frame fashion, how can I just convert the whole-genome assembly (several mega-base level chorosomes) to NLR-parser-recognized protein sequences? I don't suppose that translating one whole choromsome using the "translate6frame" java program is making sense. 

If I just use the protein sequcnes from annotated gene models but NOT the genomic DNA-translated protein sequcnes, will the performance of NLR-parser drop?

Many thanks
Hongbo

**Comment by steuernb** [comment]
Dear Hongbo. You are absolutely right, NLR-Parser will not perform on chromosome scale sequences. Besides running out of memory it would tell you the chromosome is associated with an NLR and there are likely more than one NLRs in the sequence. 
Please have a look at NLR-Annotator (https://github.com/steuernb/NLR-Annotator), which was developed because we ran into the very same difficulties. The publication is here: https://pubmed.ncbi.nlm.nih.gov/32184345/
All the best
Burkhard

**Comment by b524198065** [comment]
Thanks for your quick response! I have an another question. I found that the motifs used to identify NLR genes in NLR-parser were based on a 2012 study, is there any necessity to collect more positive and negative protein sequences and re-run the training process to generate a "updated" version of NLR motif dataset? Appreciate it.

**Comment by steuernb** [comment]
I found that the motifs are pretty good to find most canonical NLRs. There are some, such as ADR1 or some clades without LRRs where the motifs do not match well enough and you miss them. NLR-Parser or Annotator would not work with an alternative set of motifs. Developing a new version with an updated set of motifs is quite a big project and I'd love to score some funding for it. The current version of NLR-Annotator will give you a good enough set of NLRs to start with. As with any tool, it is always worth to check what other software is out there. You could chop the genome into overlapping fragments and run hmmscan with PFAM. That will require a lot of CPU hours and post-processing to parse the output, but it will find some NB-ARC domains that NLR-Annotator would miss and it gives you potential integrated domains. I found it not sensitive enough to find all LRRs though.

**Comment by b524198065** [comment]
Thanks again. I got it.
